# Generated by Django 4.0.2 on 2022-02-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0007_alter_articlepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="reading_time",
            field=models.IntegerField(default=0),
        ),
    ]
