# Generated by Django 4.0.2 on 2022-02-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0009_alter_articlepage_reading_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="categories",
        ),
        migrations.AddField(
            model_name="articlepage",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.articlecategory",
            ),
        ),
    ]
