# Generated by Django 4.0.2 on 2022-03-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0011_articlepage_search_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="search_image",
        ),
    ]
