# Generated by Django 4.0.2 on 2022-06-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_remove_articlepage_search_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
