# Generated by Django 4.0.2 on 2022-03-09 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="first_released_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
