# Generated by Django 4.0.2 on 2022-05-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0004_workpage_logo_image_alter_workpage_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="work_url",
            field=models.URLField(
                blank=True,
                help_text="Preferably use the released website. If not, use a GitHub link, if possible.",
                null=True,
            ),
        ),
    ]
