# Generated by Django 4.0.2 on 2022-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0005_workpage_work_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="show_to_public",
            field=models.BooleanField(
                default=True,
                help_text="If you want to show to the public on your personal portfolio website.",
            ),
        ),
    ]
