[[redirects]]
  from = "https://docs.google.com/document/d/1vllJAqf62EALCMJjZ-haBh8pkwMnMUOvWLUZyWPkEj0/edit?usp=sharing"
  to = "https://docs.google.com/document/d/1vllJAqf62EALCMJjZ-haBh8pkwMnMUOvWLUZyWPkEj0/edit?usp=sharing"
  status = 200
  force = true

[[redirects]]
  from = "https://errezshop.netlify.app/"
  to = "https://errezshop.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "https://blackcubes.github.io/react-weather/"
  to = "https://blackcubes.github.io/react-weather/"
  status = 200
  force = true

[[redirects]]
  from = "https://kinetotickets.herokuapp.com/"
  to = "https://kinetotickets.herokuapp.com/"
  status = 200
  force = true

[[redirects]]
  from = "https://filmecommerce.com/"
  to = "https://filmecommerce.com/"
  status = 200
  force = true

[[redirects]]
  from = "https://github.com/blackcubes"
  to = "https://github.com/blackcubes"
  status = 200
  force = true

[[redirects]]
  from = "https://www.linkedin.com/in/eliasgutierrez1991/"
  to = "https://www.linkedin.com/in/eliasgutierrez1991/"
  status = 200
  force = true

[[redirects]]
  from = "https://vimeo.com/blackcubes"
  to = "https://vimeo.com/blackcubes"
  status = 200
  force = true

[[redirects]]
  from = "https://www.facebook.com/elias.gutierrez.5283/"
  to = "https://www.facebook.com/elias.gutierrez.5283/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200